### ISSUE TITLE
Out of memory for ~1GB corpus

### ISSUE THREAD

**Issue by tim5go** [indiejoseph/chinese-char-rnn#4]
I am using around 1GB Chinese data for training.
My server has around 30GB RAM, but it is still running out of memory.
May I know what is the proper hardware setting for such a corpus?
Thanks~

**Comment by godmo** [comment]
請問作者會更新到Tensotflow 1.2 或是用Keras改寫嗎?謝謝~

**Comment by indiejoseph** [comment]
@tim5go how is your batch size? i usually control the batch size / seq length to avoid OOM

**Comment by indiejoseph** [comment]
@godmo 想改寫用 Tensorflow 1.x+

**Comment by tim5go** [comment]
@indiejoseph 
I used the default batch_size only, maybe is too large for huge corpus?

**Comment by indiejoseph** [comment]
@tim5go so you could try with only 1 batch first
